name: Backend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/backend/**'

  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: starter/backend
        run: pipenv install --dev

      - name: Run Linter
        working-directory: starter/backend
        run: pipenv run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: starter/backend
        run: pipenv install --dev

      - name: Run Tests
        working-directory: starter/backend
        run: pipenv run test

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        working-directory: starter/backend
        run: docker build -t mp-backend:latest .
